spring.application.name=harmoGestionWeb
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
server.port=9001
fr.afpa.cda19.harmogestionweb.api-url=http://localhost:9002