spring.application.name=harmoGestionWeb
server.port=8081

# URL de l'API
api.base.url=http://localhost:8080

# Locale FR pour formats de dates
spring.web.locale=fr_FR
spring.web.locale-resolver=fixed
